const prData = [
  {
    "index": 0,
    "vat_on_wholesale_trade_margin": 0.27,
    "splOnWholesaleTradeMargin": 0,
    "wholesale_trade_margin": 2.73,
    "Aret60": 414.75,
    "assessment_value": 0,
    "RET": 302,
    "code": 1713305,
    "dispatchDateTime": "01-03-2025",
    "supplierCode": "1603-M/s Arthos Breweries Ltd",
    "productCode": "1603B1250GBS",
    "baiscPricepercase": 395,
    "brandName": "KARJURA XTRA STRONG BEER",
    "brandCode": "1250-KARJURA XTRA STRONG BEER",
    "productSize": "BS",
    "unitPerCase": 12,
    "sold_cases": 1,
    "sold_part_bottles": 0,
    "rate_of_special_margin_value": 546.04,
    "landing_cost": 496.4,
    "sold_total_bottles": 12,
    "basic_value": 395,
    "sp_fee_value": 414.92,
    "vat_value": 49.64,
    "aed_value": 0,
    "issue_price_value": 1510,
    "additional_privilege_value": 6.24,
    "aret_value": 564,
    "cess_value": 9.93,
    "sale_value": 2090.17,
    "splFeeIcdc": 0,
    "size": 650,
    "assignedDepot": "076-Excise Depot Nellore",
    "vendorType": "2B",
    "districtName": "SPR Nellore",
    "cirleName": "Nellore-1",
    "mandalName": "Nellore Municipal Corporation",
    "mrp": 180,
    "custom_duty_percase": 0,
    "basicPrice": 395,
    "brandType": "BEER"
  },
  {
    "index": 1,
    "vat_on_wholesale_trade_margin": 0.27,
    "splOnWholesaleTradeMargin": 0,
    "wholesale_trade_margin": 2.73,
    "Aret60": 414.75,
    "assessment_value": 0,
    "RET": 302,
    "code": 1713324,
    "dispatchDateTime": "07-03-2025",
    "supplierCode": "1603-M/s Arthos Breweries Ltd",
    "productCode": "1603B1250GBS",
    "baiscPricepercase": 395,
    "brandName": "KARJURA XTRA STRONG BEER",
    "brandCode": "1250-KARJURA XTRA STRONG BEER",
    "productSize": "BS",
    "unitPerCase": 12,
    "sold_cases": 1,
    "sold_part_bottles": 0,
    "rate_of_special_margin_value": 546.04,
    "landing_cost": 496.4,
    "sold_total_bottles": 12,
    "basic_value": 395,
    "sp_fee_value": 414.92,
    "vat_value": 49.64,
    "aed_value": 0,
    "issue_price_value": 1510,
    "additional_privilege_value": 6.24,
    "aret_value": 564,
    "cess_value": 9.93,
    "sale_value": 2090.17,
    "splFeeIcdc": 0,
    "size": 650,
    "assignedDepot": "078-Excise Depot Guntur-I",
    "vendorType": "2B",
    "districtName": "Guntur",
    "cirleName": "Guntur-1",
    "mandalName": "Guntur East",
    "mrp": 180,
    "custom_duty_percase": 0,
    "basicPrice": 395,
    "brandType": "BEER"
  },
  {
    "index": 2,
    "excise_duty_value": 507.0,
    "custom_duty_value": 0,
    "vat_on_wholesale_trade_margin": 1.35,
    "splOnWholesaleTradeMargin": 0,
    "wholesale_trade_margin": 13.65,
    "Aret60": 2073.75,
    "assessment_value": 0,
    "RET": 1510,
    "code": 1713349,
    "dispatchDateTime": "07-03-2025",
    "supplierCode": "1603-M/s Arthos Breweries Ltd",
    "productCode": "1603B1250GBS",
    "baiscPricepercase": 1975,
    "brandName": "KARJURA XTRA STRONG BEER",
    "brandCode": "1250-KARJURA XTRA STRONG BEER",
    "productSize": "BS",
    "unitPerCase": 12,
    "sold_cases": 5,
    "sold_part_bottles": 0,
    "rate_of_special_margin_value": 2730.2,
    "landing_cost": 2482.0,
    "sold_total_bottles": 60,
    "basic_value": 1975,
    "sp_fee_value": 2074.6,
    "vat_value": 248.2,
    "aed_value": 0,
    "issue_price_value": 7550,
    "additional_privilege_value": 31.2,
    "aret_value": 2820,
    "cess_value": 49.64,
    "sale_value": 10450.84,
    "splFeeIcdc": 0,
    "size": 650,
    "assignedDepot": "078-Excise Depot Guntur-I",
    "vendorType": "2B",
    "districtName": "Guntur",
    "cirleName": "Guntur-1",
    "mandalName": "Guntur East",
    "mrp": 180,
    "custom_duty_percase": 0,
    "basicPrice": 395,
    "brandType": "BEER"
  }
];

export { prData };